SchoolWebApplication/Controllers/MainClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using SchoolWebApplication.Models;

namespace SchoolWebApplication.Controllers
{
    public class MainClassController : Controller
    {
        private SchoolEntities2 db = new SchoolEntities2();
        //
        // GET: /MainClass/
        public ActionResult MainClassesIndex(int? UserId, int? Flag)
        {
            try {
                if (Session["LoggedUserFullName"] != null)
                {
                    if (UserId != null)
                    {
                        var user = db.Users.Find(UserId);
                        Session["LoginUser"] = "true";
                        Session["LoggedUserID"] = user.UserId;
                        Session["LoggedUserFullName"] = user.FullName;
                    }
                    if (Flag != null)
                    {
                        ViewBag.DoubleLogin = "You are already logged in as " + Session["LoggedUserFullName"];
                    }
                    else
                    {
                        ViewBag.DoubleLogin = null;
                    }
                    var classes = db.Classes.ToList();
                    return View(classes);
                }
                else
                {
                    return RedirectToAction("MainLog", "Home");
                }
                
            }
            catch(Exception e) {
                return View(e);
            }
            
        }

        [HttpPost]
        public JsonResult AddClass(string Title,int ClassRoomSeats)
        {
            try
            {
                if (Title != "" && ClassRoomSeats != 0 )
                {
                    var newClass = new Class();
                    newClass.Title = Title;
                    newClass.StudentsNum = ClassRoomSeats;
                    //if (GPA > 4 || GPA < 0) { return Json(new { status = false, message = "Invalid GPA number" }); } else { newStudent.GPA = GPA; }

                    db.Classes.Add(newClass);
                    db.SaveChanges();

                    return Json(new { status = true });
                }
                else
                {
                    return Json(new { status = false, message = "Invalid Entry" });
                }

            }
            catch (Exception exception)
            {
                return Json(new { status = false, message = exception.Message });
            }

        }

        public ActionResult MainClassesGridPartialView()
        {
            
            var classes = db.Classes.ToList();
            return PartialView(classes);
        }

        [HttpPost]
        public JsonResult Editclass(int classId, string Title, int ClassRoomSeats)
        {
            try
            {
                if (classId != 0 && Title != "" && ClassRoomSeats != 0)
                {
                    var NewClass = db.Classes.Find(classId);
                    NewClass.Title = Title;
                    NewClass.StudentsNum = ClassRoomSeats;
                    db.Entry(NewClass).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { status = true });
                }
                else
                {
                    return Json(new { status = false, message = "Invalid Entry" });
                }

            }
            catch (Exception exception)
            {
                return Json(new { status = false, message = exception.Message });
            }
        }

        [HttpGet]
        public JsonResult GetClassData(int ClassId)
        {
            var SelectedClass = db.Classes.Find(ClassId);

            Class classInfo = new Class
            {
                Title = SelectedClass.Title,
                StudentsNum = SelectedClass.StudentsNum
            };
            return Json(classInfo, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult DeleteClass(int ClassId)
        {
            try
            {
                if (ClassId != 0)
                {
                    var dataClass = db.Classes.Find(ClassId);
                    foreach(var item in dataClass.Courses)
                    {
                        dataClass.Courses.Remove(item);
                    }
                    db.Classes.Remove(dataClass);
                    db.SaveChanges();
                    return Json(new { status = true });
                }
                else
                {
                    return Json(new { status = false, message = "please try again" });
                }

            }
            catch (Exception exception)
            {
                return Json(new { status = false, message = exception.Message });
            }
        }
	

	}
}

SchoolWebApplication/Controllers/MainReportsController.cs
using SchoolWebApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolWebApplication.Shared;

namespace SchoolWebApplication.Controllers
{
    public class MainReportsController : Controller
    {
        private SchoolEntities2 db = new SchoolEntities2();
        
        // GET: /MainReports/
        public ActionResult MainCourseReportsIndex()
        {
            //ViewData["YearValues"] = new SelectList(Enumerable.Range(2010, (DateTime.Now.Year - 2010 + 1)));
            ViewData["CoursesTiltles"] = new SelectList(db.Courses, "CourseId", "Title");
            ViewData["StudentsValues"] = new SelectList("");

            return View();
        }

        [HttpPost]
        public JsonResult GetCourses(int courseId)
        {
            try
            {
                List<Student> ListStudents = new List<Student>();
                var coursess = db.Courses.ToList();
                var CourseDetails = new SchoolWebApplication.Shared.BLL.MyCourseClass();
                var selectedCourse = db.Courses.Find(courseId);
                CourseDetails.CourseId = selectedCourse.CourseId;
                CourseDetails.Title = selectedCourse.Title;
                CourseDetails.CreditHours = selectedCourse.CreditHours;
                CourseDetails.TeacherName = selectedCourse.Teacher.Name;
                CourseDetails.ClassTitle = selectedCourse.Class.Title;


                //foreach(var cls in coursess)
                //{
                foreach (var item in selectedCourse.FK_CourseStudent)
                {
                    var student = db.Students.Find(item.StudentId);
                    ListStudents.Add(student);
                   // CourseDetails.AssignedStudents = new List<Student>();
                    //studen.StudentId = student.StudentId;
                    //studen.Name = student.Name;
                    //studen.City = student.City;
                    //studen.Phone = student.Phone;

                    //CourseDetails.AssignedStudents.Add(student);
                }
                return Json(new { stList = new SelectList(ListStudents, "StudentId", "Name"), CourseDetails = CourseDetails });
                //return Json(CourseDetails);
            }
            catch(Exception e)
            {
                return Json(e);
            }
            //}

            //if (coursess != null) ViewData["StudentsValues"] = ListStudents;
            //List<SchoolWebApplication.Shared.BLL.MyCourseList> SelectedCourses = new List<SchoolWebApplication.Shared.BLL.MyCourseList>();
            //foreach (var cours in coursess)
            //{
            //    var listOfCourses = new SchoolWebApplication.Shared.BLL.MyCourseList();
            //    listOfCourses.CourseId = cours.CourseId;
            //    listOfCourses.Title = cours.Title;
            //    listOfCourses.CreditHours = cours.CreditHours;
            //    listOfCourses.TeacherName = cours.Teacher.Name;
            //    listOfCourses.ClassTitle = cours.Class.Title;

            //    SelectedCourses.Add(listOfCourses);
            //}
            //var selectedCourse = db.Courses.Find(courseId);

            
        }

        [HttpPost]
        public JsonResult GetStudentDetails(int StudentId)
        {
            var SelectedStudent = db.Students.Find(StudentId);
            //var students = SelectedClas.Students.ToList();
            List<SchoolWebApplication.Shared.BLL.MyStudentClass> ChoosenStudents = new List<SchoolWebApplication.Shared.BLL.MyStudentClass>();
            //foreach(var stud in students)
            //{
            //    var ListOfStuds = new SchoolWebApplication.Shared.BLL.MyStudentList();
            //    ListOfStuds.StudID = stud.StudentID;
            //    ListOfStuds.Name = stud.Name;
            //    ListOfStuds.City = stud.City;
            //    ListOfStuds.Phone = stud.Phone;
            //    ListOfStuds.GPA = Convert.ToDecimal(stud.GPA);

            //    ChoosenStudents.Add(ListOfStuds);
            //}
            List<BLL.MyCourseClass> coursesForSelectedStudent =new List<BLL.MyCourseClass>();
            var courses=db.Courses.ToList();
            foreach(var cors in courses)
            {
                foreach(var stud in cors.FK_CourseStudent)
                {
                    if (stud.StudentId==StudentId)
                    {
                        var newCors=new BLL.MyCourseClass();
                        newCors.CourseId=cors.CourseId;
                        newCors.Title=cors.Title;
                        newCors.ClassTitle=cors.Class.Title;
                        newCors.CreditHours=cors.CreditHours;
                        newCors.TeacherName=cors.Teacher.Name;
                        coursesForSelectedStudent.Add(newCors);
                    }
                }
            }
            
            return Json(coursesForSelectedStudent);
        }

        [HttpPost]
        public JsonResult GetDataForSearchedCreditHours(decimal val)
        {
            List<BLL.MyCourseClass> coursesForSelectedCreditHours = new List<BLL.MyCourseClass>();
            var courses = db.Courses.ToList();
            foreach (var Cors in courses)
            {
                if (val == Cors.CreditHours)
                {
                    var newCors = new BLL.MyCourseClass();
                    newCors.CourseId = Cors.CourseId;
                    newCors.Title = Cors.Title;
                    newCors.ClassTitle = Cors.Class.Title;
                    newCors.CreditHours = Cors.CreditHours;
                    newCors.TeacherName = Cors.Teacher.Name;
                    coursesForSelectedCreditHours.Add(newCors);
                }
            }

            return Json(coursesForSelectedCreditHours);
        }

        public ActionResult MainStudentReportsIndex()
        {
            ViewData["AllStudents"] = new SelectList(db.Students, "StudentId", "Name");
            ViewData["CoursesTitles"] = new SelectList("");
            return View();
        }

        [HttpPost]
        public JsonResult GetStudents(int StudentId)
        {
            try
            {
                List<Course> ListCourses = new List<Course>();
                var listOfStudentsCourseGrades = new List<BLL.StudentTranscript>();
                var students = db.Students.ToList();
                var StudentDetails = new SchoolWebApplication.Shared.BLL.MyStudentClass();
                var selectedStudent = db.Students.Find(StudentId);
                StudentDetails.StudID = selectedStudent.StudentId;
                StudentDetails.Name = selectedStudent.Name;
                StudentDetails.City = selectedStudent.City;
                StudentDetails.Phone = selectedStudent.Phone;
                
                foreach(var item in selectedStudent.FK_CourseStudent)
                {
                    var sttranscript = new BLL.StudentTranscript();
                    sttranscript.StudId = item.StudentId;
                    sttranscript.Course = item.Course.Title;
                    sttranscript.CreditHours = item.Course.CreditHours;
                    sttranscript.GradePoints = Convert.ToDecimal(item.CourseGrade);
                    listOfStudentsCourseGrades.Add(sttranscript);

                }
                decimal SumPoint=0;
                int SumCreditHours = 0;
                foreach(var stdData in listOfStudentsCourseGrades)
                {
                    SumPoint += stdData.GradePoints;
                    SumCreditHours += stdData.CreditHours;
                }
                var GpaDecimalVal = (SumPoint / SumCreditHours);
                var gpaVals=db.GPAs.ToList();
                foreach(var gpa in gpaVals)
                {
                    if(GpaDecimalVal<=gpa.MaxGrade && GpaDecimalVal>=gpa.MinGrade)
                    {
                        StudentDetails.CumulativeGPA = gpa.Gpa1;
                        break;
                    }
                }
                //StudentDetails.CumulativeGPA =



                List<BLL.CourseDetails> StudentDetailsList = new List<BLL.CourseDetails>();

                foreach (var item in selectedStudent.FK_CourseStudent)
                {
                    var cours = db.Courses.Find(item.CourseId);
                    ListCourses.Add(cours);
                    var CourseItemDetailed = new BLL.CourseDetails();
                    CourseItemDetailed.CourseTitle = item.Course.Title;
                    CourseItemDetailed.CourseGrade = Convert.ToDecimal(item.CourseGrade);
                    CourseItemDetailed.Semester = item.Semester;
                    CourseItemDetailed.ClassForCourse = item.Course.Class.Title;
                    CourseItemDetailed.TeacherForCourse = item.Course.Teacher.Name;
                    StudentDetailsList.Add(CourseItemDetailed);

                    // CourseDetails.AssignedStudents = new List<Student>();
                    //studen.StudentId = student.StudentId;
                    //studen.Name = student.Name;
                    //studen.City = student.City;
                    //studen.Phone = student.Phone;

                    //CourseDetails.AssignedStudents.Add(student);
                }
                return Json(new { corsList = new SelectList(ListCourses, "CourseId", "Title"), StudentDetailsList = StudentDetailsList, StudentDetails = StudentDetails });
                //return Json(CourseDetails);
            }
            catch (Exception e)
            {
                return Json(e);
            }
        }

        [HttpPost]
        public JsonResult GetStudentForCourse(int CourseId)
        {
            var course = db.Courses.Find(CourseId);
            var StudListForSelectedCourse = new List<BLL.MyStudentClass>();
            foreach(var stud in course.FK_CourseStudent)
            {
                var st=new BLL.MyStudentClass();

SchoolWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - School Web App</title>
    @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/themes/jquery-ui.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.1.4.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
@if (Session["LoginUser"] == "true")
{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (Session["LoginUser"] == "true") { 
                    @Html.ActionLink("Log Out", "MainLogOut", "Home", null, new { @class = "navbar-brand" })
                } @*else { 
                if (Session["LoginUser"] == null || Session["LoginUser"]=="false")
                {
                    @Html.ActionLink("Login", "MainLog", "Home", null, new { @class = "navbar-brand" })    
                }*@
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "MainPage", "Home")</li>
                    <li>@Html.ActionLink("Teachers", "MainTeachersIndex", "MainTeacher")</li>
                    <li>@Html.ActionLink("Students", "MainStudentsIndex", "MainStudent")</li>
                    <li>@Html.ActionLink("Classes", "MainClassesIndex", "MainClass")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle fw600 p15" data-toggle="dropdown">
                            <b class="fa  fa-user-md"></b>
                            <span><strong>Reports</strong></span>
                            <span class="caret caret-tp"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-persist pn w250 bg-white" role="menu">

                            <li class="br-t of-h">
                                <a href="@Url.Action("MainCourseReportsIndex", "MainReports")" class="fw600 p12 animated animated-short fadeInDown">
                                    <span class="fa fa-gear pr5"></span> Courses Report
                                </a>
                            </li>
                            <li class="br-t of-h">
                                <a href="@Url.Action("MainStudentReportsIndex", "MainReports")" class="fw600 p12 animated animated-short fadeInDown">
                                    <span class="fa fa-power-off pr5"></span>Students Report
                                </a>
                            </li>
                            <li class="br-t of-h">
                                <a href="@Url.Action("", "MainReports")" class="fw600 p12 animated animated-short fadeInDown">
                                    <span class="fa fa-gear pr5"></span> Teacher Report
                                </a>
                            </li>
                            <li class="br-t of-h">
                                <a href="@Url.Action("", "MainReports")" class="fw600 p12 animated animated-short fadeInDown">
                                    <span class="fa fa-power-off pr5"></span>Class Report
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
                
                @*@Html.Partial("_LoginPartial")*@
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li class="br-t of-h">
                    <a class="fw600 p12 animated animated-short fadeInDown" style="font-family:Arial;font-size:large;color:white">
                        Welcome @Session["LoggedUserFullName"].ToString()
                    </a>
                </li>
</ul>
        </div>
    </div>
    }
    <div class="container body-content">
        
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>

    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SchoolWebApplication/Views/Shared/_LayoutNew.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <style type="text/css">
        table {
            margin: 4px;
            border-collapse: collapse;
            width: 500px;
            font-family: Tahoma;
            font-size: small;
        }

        th {
            background-color: #990000;
            font-weight: bold;
            color: White !important;
        }

        table th a {
            color: White;
            text-decoration: none;
        }

        #subGrid th {
            background-color: #021D39;
        }

        table th, table td {
            border: 1px solid black;
            padding: 5px;
        }

        .ExpColl {
            cursor: pointer;
        }

        .expand {
            background-color: Red;
            width: 10px;
            height: 10px;
        }

        .collapse {
            background-color: Green;
            width: 10px;
            height: 10px;
        }
    </style>
</body>
</html>